### ISSUE TITLE
Deserialization failure when using borrowed `&str` in `serde_conv!()`

### ISSUE THREAD

**Issue by qtisan** [jonasbb/serde_with#620]
See the code:

I successfully serialize `std::backtrace::Backtrace`, but cannot deserialize it.
When `serde_json::from_str::<Error>()` is called,  it cause `serde_json::Error`.

Is it something wrong with the type `Result<Error, serde_json::error::Error>`? duplicated name?

I cannot find where goes wrong, and the `----backtrace----` bar is not printed.

```rs
use serde::{Deserialize, Serialize};
use serde_with::serde_as;
use std::backtrace::Backtrace;

serde_with::serde_conv!(
    SerdeBacktrace,
    Backtrace,
    |v: &Backtrace| v.to_string(),
    |_: &str| -> std::result::Result<_, std::convert::Infallible> {
        // DEBUG: serde_json::from_str::<Error> do not reach here
        println!("----------------backtrace------------------");
        Ok(Backtrace::capture())
    }
);

#[serde_as]
#[derive(Serialize, Deserialize, Debug)]
struct Error {
    message: String,
    #[serde_as(as = "SerdeBacktrace")]
    backtrace: Backtrace,
}
impl Error {
    fn new(msg: &str) -> Self {
        Self {
            message: msg.to_string(),
            backtrace: Backtrace::capture(),
        }
    }
}

#[test]
fn test_error() {
    let err = Error::new("will convert");
    let json_str = serde_json::to_string(&err).unwrap();
    println!("{}", json_str);
    assert!(json_str.contains("will convert"));

    println!("----------------------------------devider-----------------------");
    // anonymous Result<Error, serde_json::error::Error>
    let deserialized_r = match serde_json::from_str::<Error>(&json_str) {
        Ok(v) => v,
        // FIXME: will cause invalid type: string: [the backtrace string]
        Err(e) => Error::new(format!("convert error: cause: {}", e).as_str()),
    };
    println!("der: {:?}", deserialized_r);
    // This assertion will fail
    assert!(deserialized_r.message.contains("will convert"));
}

```

```
running 1 test
{"message":"will convert","backtrace":"   0: std::backtrace_rs::backtrace::libunwind::trace\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5\n   1: std::backtrace_rs::backtrace::trace_unsynchronized\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5\n   2: std::backtrace::Backtrace::create\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/backtrace.rs:332:13\n   3: std::backtrace::Backtrace::capture\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/backtrace.rs:298:9\n   4: playground::Error::new\n             at ./tests/playground.rs:28:24\n   5: playground::test_error\n             at ./tests/playground.rs:35:15\n   6: playground::test_error::{{closure}}\n             at ./tests/playground.rs:34:17\n   7: core::ops::function::FnOnce::call_once\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5\n   8: core::ops::function::FnOnce::call_once\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5\n   9: test::__rust_begin_short_backtrace\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:626:18\n  10: test::run_test_in_process::{{closure}}\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:649:60\n  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panic/unwind_safe.rs:271:9\n  12: std::panicking::try::do_call\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:500:40\n  13: std::panicking::try\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:464:19\n  14: std::panic::catch_unwind\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panic.rs:142:14\n  15: test::run_test_in_process\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:649:27\n  16: test::run_test::{{closure}}\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:572:43\n  17: test::run_test::{{closure}}\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:600:41\n  18: std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/sys_common/backtrace.rs:135:18\n  19: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/thread/mod.rs:529:17\n  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panic/unwind_safe.rs:271:9\n  21: std::panicking::try::do_call\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:500:40\n  22: std::panicking::try\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:464:19\n  23: std::panic::catch_unwind\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panic.rs:142:14\n  24: std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/thread/mod.rs:528:30\n  25: core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5\n  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/alloc/src/boxed.rs:2007:9\n  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/alloc/src/boxed.rs:2007:9\n  28: std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/sys/unix/thread.rs:108:17\n  29: __pthread_start\n"}
----------------------------------devider-----------------------
der: Error { message: "convert error: cause: invalid type: string \"   0: std::backtrace_rs::backtrace::libunwind::trace\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5\\n   1: std::backtrace_rs::backtrace::trace_unsynchronized\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5\\n   2: std::backtrace::Backtrace::create\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/backtrace.rs:332:13\\n   3: std::backtrace::Backtrace::capture\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/backtrace.rs:298:9\\n   4: playground::Error::new\\n             at ./tests/playground.rs:28:24\\n   5: playground::test_error\\n             at ./tests/playground.rs:35:15\\n   6: playground::test_error::{{closure}}\\n             at ./tests/playground.rs:34:17\\n   7: core::ops::function::FnOnce::call_once\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5\\n   8: core::ops::function::FnOnce::call_once\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5\\n   9: test::__rust_begin_short_backtrace\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:626:18\\n  10: test::run_test_in_process::{{closure}}\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:649:60\\n  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panic/unwind_safe.rs:271:9\\n  12: std::panicking::try::do_call\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:500:40\\n  13: std::panicking::try\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:464:19\\n  14: std::panic::catch_unwind\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panic.rs:142:14\\n  15: test::run_test_in_process\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:649:27\\n  16: test::run_test::{{closure}}\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:572:43\\n  17: test::run_test::{{closure}}\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs:600:41\\n  18: std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/sys_common/backtrace.rs:135:18\\n  19: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/thread/mod.rs:529:17\\n  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panic/unwind_safe.rs:271:9\\n  21: std::panicking::try::do_call\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:500:40\\n  22: std::panicking::try\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:464:19\\n  23: std::panic::catch_unwind\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panic.rs:142:14\\n  24: std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/thread/mod.rs:528:30\\n  25: core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5\\n  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/alloc/src/boxed.rs:2007:9\\n  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/alloc/src/boxed.rs:2007:9\\n  28: std::sys::unix::thread::Thread::new::thread_start\\n             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/sys/unix/thread.rs:108:17\\n  29: __pthread_start\\n\", expected a borrowed string at line 1 column 4326", backtrace: Backtrace [{ fn: "std::backtrace_rs::backtrace::libunwind::trace", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/../../backtrace/src/backtrace/libunwind.rs", line: 93 }, { fn: "std::backtrace_rs::backtrace::trace_unsynchronized", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/../../backtrace/src/backtrace/mod.rs", line: 66 }, { fn: "std::backtrace::Backtrace::create", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/backtrace.rs", line: 332 }, { fn: "std::backtrace::Backtrace::capture", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/backtrace.rs", line: 298 }, { fn: "playground::Error::new", file: "./tests/playground.rs", line: 28 }, { fn: "playground::test_error", file: "./tests/playground.rs", line: 45 }, { fn: "playground::test_error::{{closure}}", file: "./tests/playground.rs", line: 34 }, { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs", line: 250 }, { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs", line: 250 }, { fn: "test::__rust_begin_short_backtrace", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs", line: 626 }, { fn: "test::run_test_in_process::{{closure}}", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs", line: 649 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs", line: 500 }, { fn: "std::panicking::try", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs", line: 464 }, { fn: "std::panic::catch_unwind", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panic.rs", line: 142 }, { fn: "test::run_test_in_process", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs", line: 649 }, { fn: "test::run_test::{{closure}}", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs", line: 572 }, { fn: "test::run_test::{{closure}}", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/test/src/lib.rs", line: 600 }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/sys_common/backtrace.rs", line: 135 }, { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/thread/mod.rs", line: 529 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs", line: 500 }, { fn: "std::panicking::try", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs", line: 464 }, { fn: "std::panic::catch_unwind", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panic.rs", line: 142 }, { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/thread/mod.rs", line: 528 }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs", line: 250 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/alloc/src/boxed.rs", line: 2007 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/alloc/src/boxed.rs", line: 2007 }, { fn: "std::sys::unix::thread::Thread::new::thread_start", file: "/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/sys/unix/thread.rs", line: 108 }, { fn: "__pthread_start" }] }
thread 'test_error' panicked at 'assertion failed: deserialized_r.message.contains(\"will convert\")', src-tauri/rs-play-lib/tests/playground.rs:49:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/panicking.rs:117:5
   3: playground::test_error
             at ./tests/playground.rs:49:5
   4: playground::test_error::{{closure}}
             at ./tests/playground.rs:34:17
   5: core::ops::function::FnOnce::call_once
             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test_error ... FAILED

failures:

failures:
    test_error

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass `-p rs-play-lib --test playground`
```

**Comment by qtisan** [comment]
Dependencies:

```
serde = "1.0.171"
serde_json = "1.0.103"
serde_with = {version = "3.1.0", features = ["chrono"]}
```

**Comment by jonasbb** [comment]
Your example compiles for me when run on [rustexplorer](https://www.rustexplorer.com/b/dq0ywg).

Your error message contains the needed information why it failed: “expected a borrowed string at line 1 column 4326”. The reason is that you ask for a borrowed string (`&str`) and in your real code `serde_json` cannot provide one. Simply change the `serde_conv!` call such using this: `|_: String| -> std::result::Result<_, std::convert::Infallible> {` (i.e., owned `String` instead of `&str`).

**Comment by qtisan** [comment]
it works fine. 

thanks!
